### ISSUE TITLE
enter doesnt work to start search

### ISSUE THREAD

**Issue by tooomm** [tooomm/github-release-stats#1]
`Enter` doesn't swap the input cursor from the name field to the repo field.

Additionally, it doesn't confirm your data and activate the search button to display the results once you're done.

**Comment by jessedp** [comment]
In case you care, I modified this further here, but far too much and not really in a pullable manner.

https://github.com/jessedp/github-release-stats

It fixes this, updates libraries, cleans up the code, makes the search area toggle-able, allows ignoring files in download stats, adds file icons. Maybe more.

**Comment by tooomm** [comment]
Awesome, your fork looks cool. A lot of nice additions.

Thanks for letting me know. Will check in detail when I get around to it! :)

**Comment by tooomm** [comment]
Thanks for pointing to your fix, added it in https://github.com/tooomm/github-release-stats/commit/5fa425b023b2d623c4671fa79dcb3cfca1310862 as well. ❤️
