### ISSUE TITLE
Create badge for repos to include in their readme

### ISSUE THREAD

**Issue by cpyarger** [tooomm/github-release-stats#23]
Pretty self explanatory

**Comment by tooomm** [comment]
Hi @cpyarger. I'm sorry, but can you clarify please?

**Comment by cpyarger** [comment]
Take a look at my repo, under readme.md status section. Those are badges (: 

https://shields.io/ allows for automatic badge generation using data from various api endpoints

**Comment by tooomm** [comment]
Oh, I know badges. :)
But I'm not sure what kind of information you would like to display.

As you pointed out, there is shields and they offer already a wide range of badges related to GitHub?

**Comment by cpyarger** [comment]
Personally, I just want the total download count lol

Warmest Regards,


Christopher P. Yarger

Phone: 802-505-7574
Skype: cpyarger

/************************************
Based upon email reliability concerns,
please send an acknowledgment in response to this note.

**Comment by tooomm** [comment]
>Personally, I just want the total download count lol

shields has that (and more) already, hence I was unsure about your request. Search for "GitHub".
The release and download ones are particularly interesting, e.g:

[![Complete Download Count](https://img.shields.io/github/downloads/cpyarger/obs-midi/total)](https://github.com/cpyarger/obs-midi/releases)
`[![Complete Download Count](https://img.shields.io/github/downloads/cpyarger/obs-midi/total)](https://github.com/cpyarger/obs-midi/releases)` 

Closing this.
