### ISSUE TITLE
Website does not respond to new requests

### ISSUE THREAD

**Issue by Stendarpaval** [tooomm/github-release-stats#26]
Sorry if this is the wrong place to report this, but the instance of this project hosted at https://tooomm.github.io/github-release-stats/ seems to have stopped responding to new requests since yesterday. Instead it just shows the loader.gif animation. 

I want to add that this tool has provided me many usage insights in the status of my projects, as well as a quick method of verifying that new releases are properly accessible. So thank you for hosting it!

**Comment by kid2407** [comment]
Should be fixed with commit ba21fffed10b9bb29dccdda54e6e409364102ab9.

**Comment by Stendarpaval** [comment]
Indeed it is! Thank you. I'll go ahead and close this issue.
